// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD6_yqIiayAxBhLMF7GtzcOe8s_CypbAA',
    appId: '1:940514634281:web:1359e47a8f509646b94a38',
    messagingSenderId: '940514634281',
    projectId: 'final-depi-project',
    authDomain: 'final-depi-project.firebaseapp.com',
    storageBucket: 'final-depi-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ-C17J37eYZwKpVJ9TIlQDvvzjJ4xehE',
    appId: '1:940514634281:android:9573e44771f42046b94a38',
    messagingSenderId: '940514634281',
    projectId: 'final-depi-project',
    storageBucket: 'final-depi-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5jeKe1Nv2FpAjNuRCedzifld7ITSTNtw',
    appId: '1:940514634281:ios:bab1799df7d586fab94a38',
    messagingSenderId: '940514634281',
    projectId: 'final-depi-project',
    storageBucket: 'final-depi-project.firebasestorage.app',
    iosBundleId: 'com.example.depiFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5jeKe1Nv2FpAjNuRCedzifld7ITSTNtw',
    appId: '1:940514634281:ios:bab1799df7d586fab94a38',
    messagingSenderId: '940514634281',
    projectId: 'final-depi-project',
    storageBucket: 'final-depi-project.firebasestorage.app',
    iosBundleId: 'com.example.depiFinalProject',
  );
}
